### ISSUE TITLE
jsonModify not encoding return chars

### ISSUE THREAD

**Issue by DelfsEngineering** [dansmith65/FileMaker-JSON-Functions#38]
The following two functions should return the same key:value pairs

Although this may not be addressed with the upcoming FM v16 incorporating CF's  it should be documented as many people will keep these CF's in their systems.

`jsonModify ( "{}"; "returnTest" ; "first¶Second" ) 
& ¶ &
jsonOp ( "returnTest" ; "first¶Second" )`

Current result:
`{"returnTest":"first¶Second"}
"returnTest":"first\rSecond",`

Work around:
' jsonModify ( "{}"; "returnTest" ; Substitute ( "first¶Second"; "¶" ; "\r" )  ) `

**Comment by dansmith65** [comment]
Accurate bug report, but done on the wrong repo. It should be posted here instead: https://github.com/geistinteractive/JSONCustomFunctions. Both projects have functions with the same name, that do the same thing, so it's an easy mistake to make!

I ran your test with my non-plugin backed json functions and they both produce an `\r` separator as expected.
